### ISSUE TITLE
Multiple JWT token verification public key option.

### ISSUE THREAD

**Issue by antoniomerlin** [frbuceta/restify-jwt-community#123]
```
server.use(rJwt({
    "secret" : fs.readFileSync(config.app.jwt_pub, 'utf8')
}).unless({
    path: ['/path']
}));
```

Is their a way we can add multiple public key in secret option

**Comment by frbuceta** [comment]
> ```
> server.use(rJwt({
>     "secret" : fs.readFileSync(config.app.jwt_pub, 'utf8')
> }).unless({
>     path: ['/path']
> }));
> ```
> 
> Is their a way we can add multiple public key in secret option

I do not understand what you mean

**Comment by antoniomerlin** [comment]
means can we add multiple public files.
no worry i've solved as per my requirements
