### ISSUE TITLE
Shared Secret

### ISSUE THREAD

**Issue by KidSysco** [frbuceta/restify-jwt-community#61]
What is the Shared Secret that is mentioned in the usage examples?

I don't understand how the shared secret is specified or used.

Any insight is appreciated.

**Comment by frbuceta** [comment]
Not sure what he means. Here is an introduction to JWT (https://jwt.io/introduction/). The secret generated by the token must be the same that verifies it.
On this page (https://jwt.io/ ) you can test how your tokens work

**Comment by KidSysco** [comment]
The documentation provided by this library does not explain how to implement a Shared Secret.

There is just an arbitrary example with shhhhhhhared-secret in it, and no further explanation.

That does not explain how the token is generated by this library, nor does it explain how the token is verified.

So here is my question... In the example pulled from the docs...

```
const rJWT = require('restify-jwt-community');

app.get('/protected',
  rJWT({secret: 'shhhhhhared-secret'}),
  function(req, res) {
    if (!req.user.admin) return res.send(401);
    res.send(200);
  });
```

Where is the secret generated by the token or verified?

Any insight you have is appreciated.

Thanks

**Comment by KidSysco** [comment]
The only thing I can think of... is that we are expected to put the words shhhhhhared-secret into the code there, and then this just works? How is that secure? Usually a shared Secret is specified on both sides of a connection. If each party does not have the shared secret, then it doesn't work, so who are the two parties here? This is extremely confusing.

**Comment by KidSysco** [comment]
I guess I expected JWT to work differently than this. I expected to simply store a token in the DB to identify users. But it seems that users need to generate and specify some sort of shared secret to work with this library between the browser and the server?

Sorry, I am just thinking out loud, and I am obviously confused.

**Comment by KidSysco** [comment]
Furthermore, the link you sent me to does not recommend a Shared Secret in JWT. If you read the article carefully, the article indicates that Simple Web Tokens use Shared Secrets.

```
Security-wise, SWT can only be symmetrically signed by a shared secret using the HMAC algorithm.
```

**Comment by KidSysco** [comment]
https://jwt.io/introduction/

**Comment by KidSysco** [comment]
Perhaps a more real world example of how this library is expected to be used should be posted.

**Comment by KidSysco** [comment]
For example, I cannot use the words shhhhared-secret, because it is supposed to be a secret. So I would expect there to be some instructions saying something like....

You need to generate a shared secret of your own and keep it safe and specify it here on the client. Then pass it to the services like this, and show an example.

**Comment by frbuceta** [comment]
The key that you are going to put in 'secret' is like a password that only the server will have and that you need to generate the token and to verify it on the server, it never goes out of the server.

```
const rJWT = require('restify-jwt-community');

const mySecret = 'MySecretString'

app.get('/protected',
  rJWT({secret: mySecret}),
  function(req, res) {
    if (!req.user.admin) return res.send(401);
    res.send(200);
  });

app.get('/'login, (req, res) => {
  const token = jwt.sign(
    {
      admin: true
    },
    mySecret
  )
  res.send({ token })
})
```

Maybe I should update the documentation to explain better, but this is an example

**Comment by KidSysco** [comment]
oh wow, very interesting input. Thank you for the clarification, I was really struggling with that one! hahahaha!

That is a great start. Your explanation could use a bit more work, but that really helps.

So correct me if wrong...

This means we do not need to do much with the secret, other than set it once, likely in a config file, and keep it secret of course.

What would you do if the secret was compromised? Say that it got checked into a public repo on GitHub for example. Should I change the secret in my production app right away? How would that action effect the login of existing users? I suppose.... It would result in a failure for requests that did not have matching secrets, but since most of that happens inside the server in a single request.... Then nothing would happen at all by changing the secret in production in mid day, right?

**Comment by frbuceta** [comment]
If the secret were compromised, I should change it. When changing all users who have a token, they will be required to log in again.
You can also pass the secret through an environment variable using `process.env.JWT_SECRET`, for example.

You can try the example (https://frbuceta.github.io/restify-jwt-community/examples#single-example) I have in the documentation using postman (https://www.getpostman.com/)

Here is a tutorial on how to start using postman https://learning.getpostman.com/getting-started/
The url of the example is https://hndr4.sse.codesandbox.io
And the code you can look at https://codesandbox.io/s/rjwt-single-example-hndr4?from-embed, you can also modify it and try it online

**Comment by KidSysco** [comment]
Great, thanks for the input.

I also found a good write up this morning here...

https://medium.com/sean3z/json-web-tokens-jwt-with-restify-bfe5c4907e3c

I will probably have more questions soon. Thanks for your help!

**Comment by frbuceta** [comment]
> https://medium.com/sean3z/json-web-tokens-jwt-with-restify-bfe5c4907e3c

Interesting, cool!

> I will probably have more questions soon. Thanks for your help!

I am happy to help you
