### ISSUE TITLE
.git directory in NPM

### ISSUE THREAD

**Issue by ZacharyDraper** [frbuceta/restify-jwt-community#8]
Hi guys,

It looks like the NPM package contains your .git folder in version 1.0.10  which is preventing `npm install` from running after the newest version of your package is installed.

To test, run `npm install` on a repo that includes this package. Once installed, run `npm install` again. You will see something similar to the following:

```
npm ERR! path /Users/zachary/Talage-Code/Code-API/node_modules/restify-jwt-community
npm ERR! code EISGIT
npm ERR! git /Users/zachary/Talage-Code/Code-API/node_modules/restify-jwt-community: Appears to be a git repo or submodule.
npm ERR! git     /Users/zachary/Talage-Code/Code-API/node_modules/restify-jwt-community
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

This will cause `npm install` to fail.

**Comment by frbuceta** [comment]
Mmm I miss, I investigate

**Comment by frbuceta** [comment]
Fixed, Thanks for letting me know;)

Version 1.0.10 is deprecated "https://www.npmjs.com/package/restify-jwt-community/v/1.0.10"

**Comment by frbuceta** [comment]
https://www.npmjs.com/package/restify-jwt-community/v/1.0.10
